### ISSUE TITLE
FEAT: Restrict Registration

### ISSUE THREAD

**Issue by nhalstead** [TimWitzdam/GitSave#2]
[Reading the registration code](https://github.com/TimWitzdam/GitSave/blob/main/server.js#L67), it looks like anyone can register users. (I'd imagine people wouldn't host this publicly facing, but conversely their is no guide to configure this behind a reverse proxy 😉).

Adding an option through either environment variables (preferred) or a config file could allow configuration of registration restrictions, [like rallly](https://github.com/lukevella/rallly/blob/5abb94367610c38cbf6f3b55be39a5a474c5fd8c/apps/web/src/utils/auth.ts#L309). You don't use email addresses like rallly does, so it would have to be a flag to disable registration all together, or require a invite key.

```env

# If the value is set, the create user page will require one of the keys listed below.
REGISTER_KEYS=rick-ashley,no-secure-key,foobar

# Enable or Disable the registration page.
DISABLE_REGISTRATION=1

```

> [DISABLE_REGISTRATION (gitea)](https://docs.gitea.com/administration/config-cheat-sheet#service-service)

**Comment by TimWitzdam** [comment]
Hey, thanks for the idea and concern about the security of the users!

GitSave is currently built for just a single user (which can be registered at setup). There's no way for anyone to create a second user unless they change the code or edit the database directly. So the `DISABLE_REGISTRATION=1` would basically be set automatically after the setup first user is created.

I'll keep this suggestion in mind for the future, when adding support for multiple accounts.

Do you agree this is fine or did I miss your point?

**Comment by nhalstead** [comment]
Ahh I didn't see the middleware: [userExistCheck](https://github.com/TimWitzdam/GitSave/blob/main/src/middleware/userExistCheck.js#L3)
